// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using CQRS.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace CQRS.Infra.Context
{
    public class ControletodosContext : DbContext
    {
        public ControletodosContext()
        {
        }

        public ControletodosContext(DbContextOptions<ControletodosContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Todo> Todo { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseSqlServer("Data Source=NB317-WAS6\\SQLEXPRESS;Initial Catalog=ControleTodos;Integrated Security=True;");
            }
            
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {   
            base.OnModelCreating(modelBuilder);
        }
    }
}